### ISSUE TITLE
Integrate QRAO

### ISSUE THREAD

**Issue by t-imamichi** [qiskit-community/qiskit-optimization#473]
### What should we add?

Integrate [qrao-prototype](https://github.com/qiskit-community/prototype-qrao) into Qiskit optimization.

- [ ] discuss whether `to_ising` returns identity matrix as offset instead of returning `offset` float value
  - Currently: `operator, offset = qp.to_ising()`
  - Newly: `operator = qp.to_ising()`
  - In order not to break API, introducing an option to control output may be useful, e.g., `to_ising(offset: bool)` to return operator and offset if `offset=True`, otherwise return only operator.
- [ ] magic rounding needs to be migrated to sampler
- [ ] refactor `solve` so that QRAO solver can access the problem to be encoded
- [ ] discuss whether allow pytest for unit tests because qrao-prototype uses pytest for unit tests.

**Comment by garrison** [comment]
Some comments to follow up on the above points:
- There is an open PR to deprecate `offset`: https://github.com/qiskit-community/prototype-qrao/pull/14
- There is an open issue for migrating magic rounding to the sampler: https://github.com/qiskit-community/prototype-qrao/issues/21
- There is a draft PR for generating the encoding on the fly: https://github.com/qiskit-community/prototype-qrao/pull/13, with the corresponding issue at https://github.com/qiskit-community/prototype-qrao/issues/9.

**Comment by t-imamichi** [comment]
This might be related too #325
